name: publish
on: [push]
jobs:
  publish-demo-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the hello-docker Docker image
        run: |
              docker build . --tag ghcr.io/AaronLison/demo-ghcr:latest
              docker run ghcr.io/AaronLison/demo-ghcr:latest
              docker push ghcr.io/AaronLison/demo-ghcr:latest
